apiVersion: apps/v1
kind: Deployment
metadata:
  name: diplomaapp
  labels:
    app.kubernetes.io/name: diplomaapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app.kubernetes.io/name: diplomaapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: diplomaapp
    spec:
      containers:
      - name: diplomaapp
        image: chuckberry321/diplomaapp:latest
        resources:
          requests:
            memory: "24Mi"
            cpu: "32m"
          limits:
            memory: "48Mi"
            cpu: "64m"
        ports:
        - containerPort: 80
