apiVersion: v1
kind: Service
metadata:
  name: diplomaapp
  namespace: test-app
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: diplomaapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31000
