apiVersion: apps/v1
kind: Deployment
metadata:
  name: diploma-app
  labels:
    app.kubernetes.io/name: diploma-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app.kubernetes.io/name: diploma-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: diploma-app
    spec:
      containers:
      - name: diploma-app
        image: chuckberry321/diploma-app:latest
        resources:
          requests:
            memory: "24Mi"
            cpu: "32m"
          limits:
            memory: "48Mi"
            cpu: "64m"
        ports:
        - containerPort: 80
