apiVersion: v1
kind: Service
metadata:
  name: diploma-app-nginx
  namespace: test-app
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: diploma-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: {{ .Values.diploma-app_service.nodeport }}
