replicaCount: 1

diplomaapp_deployment:
  image:
    repository: chuckberry321/diplomaapp
    tag: latest
  resources:
    requests: 
      memory: "24Mi"
      cpu: "32m"
    limits:
      memory: "48Mi"
      cpu: "64m"
  replicaCount: 5

diplomaapp_service:
  nodeport: 31000

