replicaCount: 1

diploma-app_deployment:
  image:
    repository: chuckberry321/diploma-app
    tag: latest
  resources:
    requests: 
      memory: "24Mi"
      cpu: "32m"
    limits:
      memory: "48Mi"
      cpu: "64m"
  replicaCount: 5

diploma-app_service:
  nodeport: 33080

