apiVersion: v1
kind: Service
metadata:
  name: diplomaapp-nginx
  namespace: test-app
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: diplomaapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: {{ .Values.diplomaapp_service.nodeport }}
